spring:
    thread-executor: virtual
    lifecycle:
        timeout-per-shutdown-phase: "20s"
    main:
        banner-mode: off
    jpa:
        generate-ddl: true
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: update
                format_sql: true
                show-sql: true
    jackson:
        time-zone: UTC
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    freemarker:
        cache: false
    devtools:
        restart:
            enabled: true
            additional-paths: g:/Java/WebServices, g:/Java/data
        livereload:
            enabled: true
    cache:
        type: redis
        redis:
            time-to-live: PT10M
            cache-null-values: false
            use-key-prefix: false
    servlet:
        multipart:
            max-request-size: 1MB
            max-file-size: 1MB

server:
    compression:
        enabled: true
    error:
        include-message: always
    shutdown: "graceful"

logging:
    level:
        root: WARN
        web: INFO
        meetona: INFO
        org.flywaydb: WARN
#        org.springframework.security: INFO


management:
    endpoints:
        web:
            exposure:
                include: "*"